[project]
name = "new-project"
version = "0.1.0"
description = "A python project"
authors = ["Cactuz <104035252+Qwacktuz@users.noreply.github.com>"]
channels = ["conda-forge"]                                         # package source
platforms = ["osx-arm64", "linux-64"]

[tasks]
# pixi run test/start/lint
start = "python main.py"
test = "pytest"
lint = "ruff check ."

[dependencies]
python = "3.15.*"
ruff = "*"
basedpyright = "*"

#matplotlib
#numpy
#pandas
